Map: 100%|██████████| 8551/8551 [00:00<00:00, 13062.78 examples/s]
Map: 100%|██████████| 1043/1043 [00:00<00:00, 13173.79 examples/s]
/home/ngin/PycharmProjects/MLOpsBasics/.venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_checkpoint.py:653: Checkpoint directory /home/ngin/PycharmProjects/MLOpsBasics/Week_0-Python-Lightning/models exists and is not empty.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]
  | Name                   | Type            | Params
-----------------------------------------------------------
0 | bert                   | BertModel       | 4.4 M
1 | W                      | Linear          | 258
2 | train_accuracy_metric  | BinaryAccuracy  | 0
3 | val_accuracy_metric    | BinaryAccuracy  | 0
4 | f1_metric              | BinaryF1Score   | 0
5 | precision_macro_metric | BinaryPrecision | 0
6 | recall_macro_metric    | BinaryRecall    | 0
7 | precision_micro_metric | BinaryPrecision | 0
8 | recall_micro_metric    | BinaryRecall    | 0
-----------------------------------------------------------
4.4 M     Trainable params
0         Non-trainable params
4.4 M     Total params
17.545    Total estimated model params size (MB)
/home/ngin/PycharmProjects/MLOpsBasics/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:441: The 'val_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.
/home/ngin/PycharmProjects/MLOpsBasics/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:441: The 'train_dataloader' does not have many workers which may be a bottleneck. Consider increasing the value of the `num_workers` argument` to `num_workers=11` in the `DataLoader` to improve performance.




Epoch 0:  98%|█████████▊| 262/268 [00:09<00:00, 28.81it/s, v_num=ve40, train/loss_step=0.594, train/acc_step=0.719]
Traceback (most recent call last):
  File "/home/ngin/PycharmProjects/MLOpsBasics/Week_0-Python-Lightning/train.py", line 30, in <module>
    trainer.fit(cola_model, cola_data)
  File "/home/ngin/PycharmProjects/MLOpsBasics/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 544, in fit
    call._call_and_handle_interrupt(
  File "/home/ngin/PycharmProjects/MLOpsBasics/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 44, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ngin/PycharmProjects/MLOpsBasics/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 580, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/ngin/PycharmProjects/MLOpsBasics/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 987, in _run
    results = self._run_stage()
  File "/home/ngin/PycharmProjects/MLOpsBasics/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1033, in _run_stage
    self.fit_loop.run()
  File "/home/ngin/PycharmProjects/MLOpsBasics/.venv/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 206, in run
    self.on_advance_end()
  File "/home/ngin/PycharmProjects/MLOpsBasics/.venv/lib/python3.10/site-packages/pytorch_lightning/loops/fit_loop.py", line 378, in on_advance_end
    call._call_callback_hooks(trainer, "on_train_epoch_end", monitoring_callbacks=True)
  File "/home/ngin/PycharmProjects/MLOpsBasics/.venv/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 208, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/home/ngin/PycharmProjects/MLOpsBasics/.venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 190, in on_train_epoch_end
    self._run_early_stopping_check(trainer)
  File "/home/ngin/PycharmProjects/MLOpsBasics/.venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 202, in _run_early_stopping_check
    if trainer.fast_dev_run or not self._validate_condition_metric(  # disable early_stopping with fast_dev_run
  File "/home/ngin/PycharmProjects/MLOpsBasics/.venv/lib/python3.10/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 153, in _validate_condition_metric
    raise RuntimeError(error_msg)

Epoch 0: 100%|██████████| 268/268 [00:09<00:00, 27.07it/s, v_num=ve40, train/loss_step=0.686, train/acc_step=0.571, valid/loss_step=0.555, valid/loss_epoch=0.629, valid/acc=0.691, valid/precision_macro=0.691, valid/recall_macro=1.000, valid/precision_micro=0.691, valid/recall_micro=1.000, valid/f1=0.814, train/loss_epoch=0.655, train/acc_epoch=0.696]